# Generated by Django 2.2.2 on 2020-10-19 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apostador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('saldo', models.FloatField(default=10.0)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_selecao', models.CharField(max_length=200)),
                ('qtd_de_titulos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_visitante', models.PositiveSmallIntegerField()),
                ('gols_desafiante', models.PositiveSmallIntegerField()),
                ('estadio', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField()),
                ('selecao_desafiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecaodesafiante', to='sistema.Selecao')),
                ('selecao_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecaovisitante', to='sistema.Selecao')),
            ],
        ),
        migrations.CreateModel(
            name='Bolao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_bolao', models.CharField(max_length=200)),
                ('premiacao', models.FloatField()),
                ('valor_disputado', models.FloatField()),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Partida')),
            ],
        ),
        migrations.CreateModel(
            name='ApostadoresVencedoresBolao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apostador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bolao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Bolao')),
            ],
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_gols_desafiante_apostado', models.PositiveSmallIntegerField()),
                ('qtd_gols_visitante_apostado', models.PositiveSmallIntegerField()),
                ('valor_da_aposta', models.FloatField(default=5.0)),
                ('apostador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bolao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Bolao')),
            ],
        ),
    ]
