# Generated by Django 2.2.2 on 2020-10-19 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aposta',
            unique_together={('apostador', 'bolao')},
        ),
        migrations.AlterUniqueTogether(
            name='apostadoresvencedoresbolao',
            unique_together={('apostador', 'bolao')},
        ),
    ]
