# Generated by Django 2.2.2 on 2020-10-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20201019_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='gols_desafiante',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='gols_visitante',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
