# Generated by Django 2.2.2 on 2020-10-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20201019_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolao',
            name='premiacao',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bolao',
            name='valor_disputado',
            field=models.FloatField(default=0.0),
        ),
    ]
